In [3]:
import numpy as np

In [4]:
kernel_size = 4
n = 1
k = 2

In [5]:
rows = cols = kernel_size * n + k

In [6]:
A = np.random.rand(rows, cols)
B = np.random.rand(rows, cols)
Cstar = A @ B

In [7]:
first4nrows = np.zeros((4*n, cols))

In [8]:
lastkrrows = np.zeros((k, cols))

In [9]:
# `a` is first 4n rows and 4n columns of A (upper left corner)
a = A[:4*n, :4*n]
# `b` is first 4n rows and last k columns of A (upper right corner)
b = A[:4*n, -k:]
# `c` is last k rows and 4n columns of A (lower left corner)
c = A[-k:, :4*n]
# `d` is last k rows and last k columns of A (lower right corner)
d = A[-k:, -k:]

In [10]:
# `a_prime` is first 4n rows and 4n columns of B (upper left corner)
a_prime = B[:4*n, :4*n]
# `b_prime` is first 4n rows and last k columns of B (upper right corner)
b_prime = B[:4*n, -k:]
# `c_prime` is last k rows and 4n columns of B (lower left corner)
c_prime = B[-k:, :4*n]
# `d_prime` is last k rows and last k columns of B (lower right corner)
d_prime = B[-k:, -k:]

In [11]:
# there are two contributions to the `first4nrows` matrix
# one is [a] * [a_prime][b_prime] where [a] is 4n x 4n and [a_prime][b_prime] is 4n x (4n + k)
# other is [b] * [c_prime][d_prime] where [b] is 4n x k and [c_prime][d_prime] is k x (4n + k)
alpha = a @ np.concatenate((a_prime, b_prime), axis=1)
first4nrows += alpha
beta = b @ np.concatenate((c_prime, d_prime), axis=1)
first4nrows += beta

In [12]:
# there are also two contributions to the `lastkrrows` matrix
# one is [c] * [a_prime][b_prime] where [c] is k x 4n and [a_prime][b_prime] is 4n x (4n + k)
# other is [d] * [c_prime][d_prime] where [d] is k x k and [c_prime][d_prime] is k x (4n + k)
gamma = c @ np.concatenate((a_prime, b_prime), axis=1)
lastkrrows += gamma
delta = d @ np.concatenate((c_prime, d_prime), axis=1)
lastkrrows += delta

In [13]:
combined = np.concatenate((first4nrows, lastkrrows), axis=0)

In [14]:
assert np.allclose(Cstar, combined)

In [15]:
# alpha it self can be split into two parts
alpha_first4n = np.zeros((4*n, 4*n))
alpha_lastk = np.zeros((4*n, k))

In [16]:
alpha_first4n = a @ a_prime
alpha_lastk = a @ b_prime
alpha_combined = np.concatenate((alpha_first4n, alpha_lastk), axis=1)
assert np.allclose(alpha, alpha_combined)

In [17]:
# ear 4x4_4x4n

In [18]:
n = 2
a_4x4 = np.asarray(
    np.arange(0, 16).reshape(4, 4)
)
b_4x4n = np.asarray(
    np.arange(0, 4 * 4 * n).reshape(4, 4 * n)
) * -1

In [19]:
a_4x4, b_4x4n

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11, -12, -13, -14, -15],
        [-16, -17, -18, -19, -20, -21, -22, -23],
        [-24, -25, -26, -27, -28, -29, -30, -31]]))

In [20]:
b_4x4n_1 = b_4x4n[:, :n]
b_4x4n_2 = b_4x4n[:, n:]

In [21]:
expected = a_4x4 @ b_4x4n

In [22]:
part1 = a_4x4 @ b_4x4n_1
part2 = a_4x4 @ b_4x4n_2
combined = np.concatenate((part1, part2), axis=1)

In [23]:
assert np.allclose(expected, combined)

In [24]:
expected

array([[ -112,  -118,  -124,  -130,  -136,  -142,  -148,  -154],
       [ -304,  -326,  -348,  -370,  -392,  -414,  -436,  -458],
       [ -496,  -534,  -572,  -610,  -648,  -686,  -724,  -762],
       [ -688,  -742,  -796,  -850,  -904,  -958, -1012, -1066]])

In [25]:
# field 4x4n_4nx4n

In [26]:
n = 2
a_4x4n = np.asarray(
    np.arange(0, 4 * 4 * n).reshape(4, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * 4 * n * n).reshape(4 * n, 4 * n)
) * -1

In [27]:
expected = a_4x4n @ b_4nx4n

In [28]:
expected

array([[-1120, -1148, -1176, -1204, -1232, -1260, -1288, -1316],
       [-2912, -3004, -3096, -3188, -3280, -3372, -3464, -3556],
       [-4704, -4860, -5016, -5172, -5328, -5484, -5640, -5796],
       [-6496, -6716, -6936, -7156, -7376, -7596, -7816, -8036]])

In [29]:
# farm 4nx4n_4nx4n

In [30]:
n = 2
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [31]:
expected = a_4nx4n @ b_4nx4n

In [32]:
expected

array([[ -1120,  -1148,  -1176,  -1204,  -1232,  -1260,  -1288,  -1316],
       [ -2912,  -3004,  -3096,  -3188,  -3280,  -3372,  -3464,  -3556],
       [ -4704,  -4860,  -5016,  -5172,  -5328,  -5484,  -5640,  -5796],
       [ -6496,  -6716,  -6936,  -7156,  -7376,  -7596,  -7816,  -8036],
       [ -8288,  -8572,  -8856,  -9140,  -9424,  -9708,  -9992, -10276],
       [-10080, -10428, -10776, -11124, -11472, -11820, -12168, -12516],
       [-11872, -12284, -12696, -13108, -13520, -13932, -14344, -14756],
       [-13664, -14140, -14616, -15092, -15568, -16044, -16520, -16996]])

In [33]:
# ear 4x4n_4nxk

In [34]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [35]:
a = a_4nx4n[:4, : 4*n]
b = b_4nx4n[:4*n, :k]

In [36]:
expected = a @ b

In [37]:
expected

array([[-1120],
       [-2912],
       [-4704],
       [-6496]])

In [38]:
# farm 4nx4n_4nxk

In [39]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [40]:
a = a_4nx4n[:, : 4*n]
b = b_4nx4n[:4*n, :k]

In [41]:
expected = a @ b

In [42]:
expected

array([[ -1120,  -1148,  -1176],
       [ -2912,  -3004,  -3096],
       [ -4704,  -4860,  -5016],
       [ -6496,  -6716,  -6936],
       [ -8288,  -8572,  -8856],
       [-10080, -10428, -10776],
       [-11872, -12284, -12696],
       [-13664, -14140, -14616]])

In [43]:
# ear 4xk_kx4n

In [44]:
n = 2
k = 2
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [45]:
a = a_4nx4n[:4, :k]
b = b_4nx4n[:k, :4*n]

In [46]:
a, b

(array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11, -12, -13, -14, -15]]))

In [47]:
expected = a @ b

In [48]:
expected

array([[  -8,   -9,  -10,  -11,  -12,  -13,  -14,  -15],
       [ -72,  -89, -106, -123, -140, -157, -174, -191],
       [-136, -169, -202, -235, -268, -301, -334, -367],
       [-200, -249, -298, -347, -396, -445, -494, -543]])

In [49]:
# farm 4nxk_kx4n

In [50]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [51]:
a = a_4nx4n[:, :k]
b = b_4nx4n[:k, :4*n]

In [52]:
expected = a @ b

In [53]:
expected

array([[   0,    0,    0,    0,    0,    0,    0,    0],
       [   0,   -8,  -16,  -24,  -32,  -40,  -48,  -56],
       [   0,  -16,  -32,  -48,  -64,  -80,  -96, -112],
       [   0,  -24,  -48,  -72,  -96, -120, -144, -168],
       [   0,  -32,  -64,  -96, -128, -160, -192, -224],
       [   0,  -40,  -80, -120, -160, -200, -240, -280],
       [   0,  -48,  -96, -144, -192, -240, -288, -336],
       [   0,  -56, -112, -168, -224, -280, -336, -392]])

In [54]:
# farm_4nxk_kxk

In [55]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12
b_4nx4n = (np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1) + -12

In [56]:
a = a_4nx4n[:, :k]
b = b_4nx4n[:k, :k]

In [57]:
a,b

(array([[12, 13, 14],
        [20, 21, 22],
        [28, 29, 30],
        [36, 37, 38],
        [44, 45, 46],
        [52, 53, 54],
        [60, 61, 62],
        [68, 69, 70]]),
 array([[-12, -13, -14],
        [-20, -21, -22],
        [-28, -29, -30]]))

In [58]:
expected = a @ b

In [59]:
expected

array([[ -796,  -835,  -874],
       [-1276, -1339, -1402],
       [-1756, -1843, -1930],
       [-2236, -2347, -2458],
       [-2716, -2851, -2986],
       [-3196, -3355, -3514],
       [-3676, -3859, -4042],
       [-4156, -4363, -4570]])

In [60]:
# ear_kx4_4x4

In [61]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [62]:
a = a_4nx4n[:k, :4]

In [63]:
b = b_4nx4n[:4, :4]

In [64]:
a_4nx4n

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [65]:
b_4nx4n

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20, -21, -22, -23],
       [-24, -25, -26, -27, -28, -29, -30, -31],
       [-32, -33, -34, -35, -36, -37, -38, -39],
       [-40, -41, -42, -43, -44, -45, -46, -47],
       [-48, -49, -50, -51, -52, -53, -54, -55],
       [-56, -57, -58, -59, -60, -61, -62, -63]])

In [66]:
a, b

(array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[  0,  -1,  -2,  -3],
        [ -8,  -9, -10, -11],
        [-16, -17, -18, -19],
        [-24, -25, -26, -27]]))

In [67]:
a @ b

array([[ -112,  -118,  -124,  -130],
       [ -496,  -534,  -572,  -610],
       [ -880,  -950, -1020, -1090]])

In [68]:
# field kx4_4x4n

In [69]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [70]:
a = a_4nx4n[:k, :4]
b = b_4nx4n[:4, :4 * n]

In [71]:
b

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20, -21, -22, -23],
       [-24, -25, -26, -27, -28, -29, -30, -31]])

In [72]:
a @ b

array([[ -112,  -118,  -124,  -130,  -136,  -142,  -148,  -154],
       [ -496,  -534,  -572,  -610,  -648,  -686,  -724,  -762],
       [ -880,  -950, -1020, -1090, -1160, -1230, -1300, -1370]])

In [73]:
# farm kx4n_4nx4n

In [74]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [75]:
a = a_4nx4n[:k, :4 * n]
b = b_4nx4n[:4 * n, :4 * n]

In [76]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [77]:
b

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20, -21, -22, -23],
       [-24, -25, -26, -27, -28, -29, -30, -31],
       [-32, -33, -34, -35, -36, -37, -38, -39],
       [-40, -41, -42, -43, -44, -45, -46, -47],
       [-48, -49, -50, -51, -52, -53, -54, -55],
       [-56, -57, -58, -59, -60, -61, -62, -63]])

In [78]:
a @ b

array([[-1120, -1148, -1176, -1204, -1232, -1260, -1288, -1316],
       [-2912, -3004, -3096, -3188, -3280, -3372, -3464, -3556],
       [-4704, -4860, -5016, -5172, -5328, -5484, -5640, -5796]])

In [79]:
# farm kx4n_4nxk

In [80]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1
a = a_4nx4n[:k, :4 * n]
b = b_4nx4n[:4 * n, :k]

In [81]:
a @ b

array([[-1120]])

In [82]:
# farm kxk_kx4n

In [83]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12
b_4nx4n = (np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12) * -1
a = a_4nx4n[:k, :k]
b = b_4nx4n[:k, :4 * n]

In [84]:
a @ b

array([[ -796,  -835,  -874,  -913,  -952,  -991, -1030, -1069],
       [-1276, -1339, -1402, -1465, -1528, -1591, -1654, -1717],
       [-1756, -1843, -1930, -2017, -2104, -2191, -2278, -2365]])

In [85]:
# farm kxk_kxk

In [86]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12
b_4nx4n = (np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12) * -1
a = a_4nx4n[:k, :k]
b = b_4nx4n[:k, :k]

In [87]:
a @ b

array([[-144]])

In [88]:
# ranch 4nx4n_4nx4nk
# that is, 4n x 4n matrix multiplied by 4n x (4n + k) matrix

In [89]:
n = 2
k = 3
a_4nkx4nk = np.asarray(
    np.arange(0, (4 * n + k) * (4 * n + k)).reshape(4 * n + k, 4 * n + k)
) * 0.1
b_4nkx4nk = a_4nkx4nk * -1

In [90]:
a = a_4nkx4nk[:4 * n, :4 * n]
a_prime = b_4nkx4nk[:4 * n, :4 * n]
b_prime = b_4nkx4nk[:4 * n, 4 * n:]

In [91]:
a @ np.concatenate((a_prime, b_prime), axis=1)

array([[ -15.4 ,  -15.68,  -15.96,  -16.24,  -16.52,  -16.8 ,  -17.08,
         -17.36,  -17.64,  -17.92,  -18.2 ],
       [ -49.28,  -50.44,  -51.6 ,  -52.76,  -53.92,  -55.08,  -56.24,
         -57.4 ,  -58.56,  -59.72,  -60.88],
       [ -83.16,  -85.2 ,  -87.24,  -89.28,  -91.32,  -93.36,  -95.4 ,
         -97.44,  -99.48, -101.52, -103.56],
       [-117.04, -119.96, -122.88, -125.8 , -128.72, -131.64, -134.56,
        -137.48, -140.4 , -143.32, -146.24],
       [-150.92, -154.72, -158.52, -162.32, -166.12, -169.92, -173.72,
        -177.52, -181.32, -185.12, -188.92],
       [-184.8 , -189.48, -194.16, -198.84, -203.52, -208.2 , -212.88,
        -217.56, -222.24, -226.92, -231.6 ],
       [-218.68, -224.24, -229.8 , -235.36, -240.92, -246.48, -252.04,
        -257.6 , -263.16, -268.72, -274.28],
       [-252.56, -259.  , -265.44, -271.88, -278.32, -284.76, -291.2 ,
        -297.64, -304.08, -310.52, -316.96]])

In [92]:
# ranch 4nxk_kx4nk
# that is, 4n x k matrix multiplied by k x (4n + k) matrix

In [93]:
n = 2
k = 1
a_4nkx4nk = np.asarray(
    np.arange(0, (4 * n + k) * (4 * n + k)).reshape(4 * n + k, 4 * n + k)
) * 0.1
b_4nkx4nk = a_4nkx4nk * -1

In [94]:
b = a_4nkx4nk[:4 * n, 4 * n:4 * n + k]
c_prime = b_4nkx4nk[4 * n:4 * n + k, :4 * n]
d_prime = b_4nkx4nk[4 * n:4 * n + k, 4 * n:]

In [95]:
b @ np.concatenate((c_prime, d_prime), axis=1)

array([[ -5.76,  -5.84,  -5.92,  -6.  ,  -6.08,  -6.16,  -6.24,  -6.32,
         -6.4 ],
       [-12.24, -12.41, -12.58, -12.75, -12.92, -13.09, -13.26, -13.43,
        -13.6 ],
       [-18.72, -18.98, -19.24, -19.5 , -19.76, -20.02, -20.28, -20.54,
        -20.8 ],
       [-25.2 , -25.55, -25.9 , -26.25, -26.6 , -26.95, -27.3 , -27.65,
        -28.  ],
       [-31.68, -32.12, -32.56, -33.  , -33.44, -33.88, -34.32, -34.76,
        -35.2 ],
       [-38.16, -38.69, -39.22, -39.75, -40.28, -40.81, -41.34, -41.87,
        -42.4 ],
       [-44.64, -45.26, -45.88, -46.5 , -47.12, -47.74, -48.36, -48.98,
        -49.6 ],
       [-51.12, -51.83, -52.54, -53.25, -53.96, -54.67, -55.38, -56.09,
        -56.8 ]])

In [96]:
# ranch kx4n_4nx4nk
# that is, k x 4n matrix multiplied by 4n x (4n + k) matrix

In [97]:
n = 2
k = 3
a_4nkx4nk = np.asarray(
    np.arange(0, (4 * n + k) * (4 * n + k)).reshape(4 * n + k, 4 * n + k)
) * 0.1
b_4nkx4nk = a_4nkx4nk * -1

In [98]:
c = a_4nkx4nk[4 * n:4 * n + k, :4 * n]
a_prime = b_4nkx4nk[:4 * n, :4 * n]
b_prime = b_4nkx4nk[:4 * n, 4 * n:]

In [99]:
c @ np.concatenate((a_prime, b_prime), axis=1)

array([[-286.44, -293.76, -301.08, -308.4 , -315.72, -323.04, -330.36,
        -337.68, -345.  , -352.32, -359.64],
       [-320.32, -328.52, -336.72, -344.92, -353.12, -361.32, -369.52,
        -377.72, -385.92, -394.12, -402.32],
       [-354.2 , -363.28, -372.36, -381.44, -390.52, -399.6 , -408.68,
        -417.76, -426.84, -435.92, -445.  ]])

In [100]:
# ranch kxk_kx4nk
# that is, k x k matrix multiplied by k x (4n + k) matrix

In [101]:
n = 2
k = 1
a_4nkx4nk = np.asarray(
    np.arange(0, (4 * n + k) * (4 * n + k)).reshape(4 * n + k, 4 * n + k)
) * 0.1
b_4nkx4nk = a_4nkx4nk * -1

In [102]:
d = a_4nkx4nk[4 * n:4 * n + k, 4 * n:4 * n + k]
c_prime = b_4nkx4nk[4 * n:4 * n + k, :4 * n]
d_prime = b_4nkx4nk[4 * n:4 * n + k, 4 * n:]

In [103]:
d @ np.concatenate((c_prime, d_prime), axis=1)

array([[-57.6, -58.4, -59.2, -60. , -60.8, -61.6, -62.4, -63.2, -64. ]])

In [104]:
# outer multiplication test

In [105]:
rows = 4
cols = 4
a = np.arange(0, rows * cols).reshape(rows, cols) + 1
b = a * -1

In [106]:
a, b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ -1,  -2,  -3,  -4],
        [ -5,  -6,  -7,  -8],
        [ -9, -10, -11, -12],
        [-13, -14, -15, -16]]))

In [107]:
a @ b

array([[ -90, -100, -110, -120],
       [-202, -228, -254, -280],
       [-314, -356, -398, -440],
       [-426, -484, -542, -600]])

In [108]:
combined = np.zeros((rows, rows))
for i in range(rows):
    combined += a[:, i].reshape(-1, 1) @ b[i, :].reshape(1, -1)

In [109]:
combined

array([[ -90., -100., -110., -120.],
       [-202., -228., -254., -280.],
       [-314., -356., -398., -440.],
       [-426., -484., -542., -600.]])

In [110]:
# farm 8nx8n_8nx4

In [111]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [112]:
a_8nx8n = a[:8 * n, :8 * n]
b_8nx4 = b[:8 * n, :4]

In [113]:
a_8nx8n @ b_8nx4

array([[ -248. ,  -249.2,  -250.4,  -251.6],
       [ -728. ,  -732.4,  -736.8,  -741.2],
       [-1208. , -1215.6, -1223.2, -1230.8],
       [-1688. , -1698.8, -1709.6, -1720.4],
       [-2168. , -2182. , -2196. , -2210. ],
       [-2648. , -2665.2, -2682.4, -2699.6],
       [-3128. , -3148.4, -3168.8, -3189.2],
       [-3608. , -3631.6, -3655.2, -3678.8],
       [-4088. , -4114.8, -4141.6, -4168.4],
       [-4568. , -4598. , -4628. , -4658. ],
       [-5048. , -5081.2, -5114.4, -5147.6],
       [-5528. , -5564.4, -5600.8, -5637.2],
       [-6008. , -6047.6, -6087.2, -6126.8],
       [-6488. , -6530.8, -6573.6, -6616.4],
       [-6968. , -7014. , -7060. , -7106. ],
       [-7448. , -7497.2, -7546.4, -7595.6]])

In [114]:
# simulated 8x8_8x8 kernel

In [115]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [116]:
a_8x8_8x8 = a[:8, :8]
b_8x8_8x8 = b[:8, :8]

In [117]:
a_8x8_8x8 @ b_8x8_8x8

array([[ -28.  ,  -28.28,  -28.56,  -28.84,  -29.12,  -29.4 ,  -29.68,
         -29.96],
       [-140.  , -141.88, -143.76, -145.64, -147.52, -149.4 , -151.28,
        -153.16],
       [-252.  , -255.48, -258.96, -262.44, -265.92, -269.4 , -272.88,
        -276.36],
       [-364.  , -369.08, -374.16, -379.24, -384.32, -389.4 , -394.48,
        -399.56],
       [-476.  , -482.68, -489.36, -496.04, -502.72, -509.4 , -516.08,
        -522.76],
       [-588.  , -596.28, -604.56, -612.84, -621.12, -629.4 , -637.68,
        -645.96],
       [-700.  , -709.88, -719.76, -729.64, -739.52, -749.4 , -759.28,
        -769.16],
       [-812.  , -823.48, -834.96, -846.44, -857.92, -869.4 , -880.88,
        -892.36]])

In [118]:
# field 8x8n_8nx8n

In [119]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [120]:
a_8x8n = a[:8, :8 * n]
b_8nx8n = b[:8 * n, :8 * n]

In [121]:
a_8x8n @ b_8nx8n

array([[ -248. ,  -249.2,  -250.4,  -251.6,  -252.8,  -254. ,  -255.2,
         -256.4,  -257.6,  -258.8,  -260. ,  -261.2,  -262.4,  -263.6,
         -264.8,  -266. ],
       [ -728. ,  -732.4,  -736.8,  -741.2,  -745.6,  -750. ,  -754.4,
         -758.8,  -763.2,  -767.6,  -772. ,  -776.4,  -780.8,  -785.2,
         -789.6,  -794. ],
       [-1208. , -1215.6, -1223.2, -1230.8, -1238.4, -1246. , -1253.6,
        -1261.2, -1268.8, -1276.4, -1284. , -1291.6, -1299.2, -1306.8,
        -1314.4, -1322. ],
       [-1688. , -1698.8, -1709.6, -1720.4, -1731.2, -1742. , -1752.8,
        -1763.6, -1774.4, -1785.2, -1796. , -1806.8, -1817.6, -1828.4,
        -1839.2, -1850. ],
       [-2168. , -2182. , -2196. , -2210. , -2224. , -2238. , -2252. ,
        -2266. , -2280. , -2294. , -2308. , -2322. , -2336. , -2350. ,
        -2364. , -2378. ],
       [-2648. , -2665.2, -2682.4, -2699.6, -2716.8, -2734. , -2751.2,
        -2768.4, -2785.6, -2802.8, -2820. , -2837.2, -2854.4, -2871.6,
        -2888

In [122]:
# farm 8nx8n_8nx8n

In [123]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [124]:
a_8nx8n = a[:8 * n, :8 * n]
b_8nx8n = b[:8 * n, :8 * n]

In [125]:
a_8nx8n @ b_8nx8n

array([[ -248. ,  -249.2,  -250.4,  -251.6,  -252.8,  -254. ,  -255.2,
         -256.4,  -257.6,  -258.8,  -260. ,  -261.2,  -262.4,  -263.6,
         -264.8,  -266. ],
       [ -728. ,  -732.4,  -736.8,  -741.2,  -745.6,  -750. ,  -754.4,
         -758.8,  -763.2,  -767.6,  -772. ,  -776.4,  -780.8,  -785.2,
         -789.6,  -794. ],
       [-1208. , -1215.6, -1223.2, -1230.8, -1238.4, -1246. , -1253.6,
        -1261.2, -1268.8, -1276.4, -1284. , -1291.6, -1299.2, -1306.8,
        -1314.4, -1322. ],
       [-1688. , -1698.8, -1709.6, -1720.4, -1731.2, -1742. , -1752.8,
        -1763.6, -1774.4, -1785.2, -1796. , -1806.8, -1817.6, -1828.4,
        -1839.2, -1850. ],
       [-2168. , -2182. , -2196. , -2210. , -2224. , -2238. , -2252. ,
        -2266. , -2280. , -2294. , -2308. , -2322. , -2336. , -2350. ,
        -2364. , -2378. ],
       [-2648. , -2665.2, -2682.4, -2699.6, -2716.8, -2734. , -2751.2,
        -2768.4, -2785.6, -2802.8, -2820. , -2837.2, -2854.4, -2871.6,
        -2888

In [126]:
# ranch 8nx8n_8nx8n4

In [127]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [130]:
a_8nx8n = a[:8 * n, :8 * n]
b_8nx8n4 = b[:8 * n, :8 * n + k]

In [131]:
a_8nx8n @ b_8nx8n4

array([[ -248. ,  -249.2,  -250.4,  -251.6,  -252.8,  -254. ,  -255.2,
         -256.4,  -257.6,  -258.8,  -260. ,  -261.2,  -262.4,  -263.6,
         -264.8,  -266. ,  -267.2,  -268.4,  -269.6,  -270.8],
       [ -728. ,  -732.4,  -736.8,  -741.2,  -745.6,  -750. ,  -754.4,
         -758.8,  -763.2,  -767.6,  -772. ,  -776.4,  -780.8,  -785.2,
         -789.6,  -794. ,  -798.4,  -802.8,  -807.2,  -811.6],
       [-1208. , -1215.6, -1223.2, -1230.8, -1238.4, -1246. , -1253.6,
        -1261.2, -1268.8, -1276.4, -1284. , -1291.6, -1299.2, -1306.8,
        -1314.4, -1322. , -1329.6, -1337.2, -1344.8, -1352.4],
       [-1688. , -1698.8, -1709.6, -1720.4, -1731.2, -1742. , -1752.8,
        -1763.6, -1774.4, -1785.2, -1796. , -1806.8, -1817.6, -1828.4,
        -1839.2, -1850. , -1860.8, -1871.6, -1882.4, -1893.2],
       [-2168. , -2182. , -2196. , -2210. , -2224. , -2238. , -2252. ,
        -2266. , -2280. , -2294. , -2308. , -2322. , -2336. , -2350. ,
        -2364. , -2378. , -2392. , -24

In [132]:
# ear 4x4_4x8

In [136]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [137]:
a_4x4 = a[:4, :4]
b_4x8 = b[:4, :8]

In [138]:
a_4x4 @ b_4x8

array([[ -2.8 ,  -2.86,  -2.92,  -2.98,  -3.04,  -3.1 ,  -3.16,  -3.22],
       [-26.8 , -27.66, -28.52, -29.38, -30.24, -31.1 , -31.96, -32.82],
       [-50.8 , -52.46, -54.12, -55.78, -57.44, -59.1 , -60.76, -62.42],
       [-74.8 , -77.26, -79.72, -82.18, -84.64, -87.1 , -89.56, -92.02]])

In [139]:
# field 4x4_4x8n

In [140]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [141]:
a_4x4 = a[:4, :4]
b_4x8n = b[:4, :8 * n]

In [142]:
a_4x4 @ b_4x8n

array([[  -2.8 ,   -2.86,   -2.92,   -2.98,   -3.04,   -3.1 ,   -3.16,
          -3.22,   -3.28,   -3.34,   -3.4 ,   -3.46,   -3.52,   -3.58,
          -3.64,   -3.7 ],
       [ -26.8 ,  -27.66,  -28.52,  -29.38,  -30.24,  -31.1 ,  -31.96,
         -32.82,  -33.68,  -34.54,  -35.4 ,  -36.26,  -37.12,  -37.98,
         -38.84,  -39.7 ],
       [ -50.8 ,  -52.46,  -54.12,  -55.78,  -57.44,  -59.1 ,  -60.76,
         -62.42,  -64.08,  -65.74,  -67.4 ,  -69.06,  -70.72,  -72.38,
         -74.04,  -75.7 ],
       [ -74.8 ,  -77.26,  -79.72,  -82.18,  -84.64,  -87.1 ,  -89.56,
         -92.02,  -94.48,  -96.94,  -99.4 , -101.86, -104.32, -106.78,
        -109.24, -111.7 ]])

In [143]:
# field 8x4_4x8n

In [144]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

In [145]:
a = a[:8, :4]
b = b[:4, :8 * n]

In [146]:
a @ b

array([[  -2.8 ,   -2.86,   -2.92,   -2.98,   -3.04,   -3.1 ,   -3.16,
          -3.22,   -3.28,   -3.34,   -3.4 ,   -3.46,   -3.52,   -3.58,
          -3.64,   -3.7 ],
       [ -26.8 ,  -27.66,  -28.52,  -29.38,  -30.24,  -31.1 ,  -31.96,
         -32.82,  -33.68,  -34.54,  -35.4 ,  -36.26,  -37.12,  -37.98,
         -38.84,  -39.7 ],
       [ -50.8 ,  -52.46,  -54.12,  -55.78,  -57.44,  -59.1 ,  -60.76,
         -62.42,  -64.08,  -65.74,  -67.4 ,  -69.06,  -70.72,  -72.38,
         -74.04,  -75.7 ],
       [ -74.8 ,  -77.26,  -79.72,  -82.18,  -84.64,  -87.1 ,  -89.56,
         -92.02,  -94.48,  -96.94,  -99.4 , -101.86, -104.32, -106.78,
        -109.24, -111.7 ],
       [ -98.8 , -102.06, -105.32, -108.58, -111.84, -115.1 , -118.36,
        -121.62, -124.88, -128.14, -131.4 , -134.66, -137.92, -141.18,
        -144.44, -147.7 ],
       [-122.8 , -126.86, -130.92, -134.98, -139.04, -143.1 , -147.16,
        -151.22, -155.28, -159.34, -163.4 , -167.46, -171.52, -175.58,
        -179.

In [147]:
# farm 8nx4_4x8n

In [148]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[:8 * n, :4]
b = b[:4, :8 * n]

In [149]:
a @ b

array([[  -2.8 ,   -2.86,   -2.92,   -2.98,   -3.04,   -3.1 ,   -3.16,
          -3.22,   -3.28,   -3.34,   -3.4 ,   -3.46,   -3.52,   -3.58,
          -3.64,   -3.7 ],
       [ -26.8 ,  -27.66,  -28.52,  -29.38,  -30.24,  -31.1 ,  -31.96,
         -32.82,  -33.68,  -34.54,  -35.4 ,  -36.26,  -37.12,  -37.98,
         -38.84,  -39.7 ],
       [ -50.8 ,  -52.46,  -54.12,  -55.78,  -57.44,  -59.1 ,  -60.76,
         -62.42,  -64.08,  -65.74,  -67.4 ,  -69.06,  -70.72,  -72.38,
         -74.04,  -75.7 ],
       [ -74.8 ,  -77.26,  -79.72,  -82.18,  -84.64,  -87.1 ,  -89.56,
         -92.02,  -94.48,  -96.94,  -99.4 , -101.86, -104.32, -106.78,
        -109.24, -111.7 ],
       [ -98.8 , -102.06, -105.32, -108.58, -111.84, -115.1 , -118.36,
        -121.62, -124.88, -128.14, -131.4 , -134.66, -137.92, -141.18,
        -144.44, -147.7 ],
       [-122.8 , -126.86, -130.92, -134.98, -139.04, -143.1 , -147.16,
        -151.22, -155.28, -159.34, -163.4 , -167.46, -171.52, -175.58,
        -179.

In [150]:
# field 8nx4_4x4

In [151]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[:8 * n, :4]
b = b[:4, :4]

In [152]:
a @ b

array([[  -2.8 ,   -2.86,   -2.92,   -2.98],
       [ -26.8 ,  -27.66,  -28.52,  -29.38],
       [ -50.8 ,  -52.46,  -54.12,  -55.78],
       [ -74.8 ,  -77.26,  -79.72,  -82.18],
       [ -98.8 , -102.06, -105.32, -108.58],
       [-122.8 , -126.86, -130.92, -134.98],
       [-146.8 , -151.66, -156.52, -161.38],
       [-170.8 , -176.46, -182.12, -187.78],
       [-194.8 , -201.26, -207.72, -214.18],
       [-218.8 , -226.06, -233.32, -240.58],
       [-242.8 , -250.86, -258.92, -266.98],
       [-266.8 , -275.66, -284.52, -293.38],
       [-290.8 , -300.46, -310.12, -319.78],
       [-314.8 , -325.26, -335.72, -346.18],
       [-338.8 , -350.06, -361.32, -372.58],
       [-362.8 , -374.86, -386.92, -398.98]])

In [153]:
# ranch 8nx4_4x8n4

In [154]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[:8 * n, -4:]
b = b[-4:, :]

In [156]:
a @ b

array([[ -246. ,  -246.7,  -247.4,  -248.1,  -248.8,  -249.5,  -250.2,
         -250.9,  -251.6,  -252.3,  -253. ,  -253.7,  -254.4,  -255.1,
         -255.8,  -256.5,  -257.2,  -257.9,  -258.6,  -259.3],
       [ -526. ,  -527.5,  -529. ,  -530.5,  -532. ,  -533.5,  -535. ,
         -536.5,  -538. ,  -539.5,  -541. ,  -542.5,  -544. ,  -545.5,
         -547. ,  -548.5,  -550. ,  -551.5,  -553. ,  -554.5],
       [ -806. ,  -808.3,  -810.6,  -812.9,  -815.2,  -817.5,  -819.8,
         -822.1,  -824.4,  -826.7,  -829. ,  -831.3,  -833.6,  -835.9,
         -838.2,  -840.5,  -842.8,  -845.1,  -847.4,  -849.7],
       [-1086. , -1089.1, -1092.2, -1095.3, -1098.4, -1101.5, -1104.6,
        -1107.7, -1110.8, -1113.9, -1117. , -1120.1, -1123.2, -1126.3,
        -1129.4, -1132.5, -1135.6, -1138.7, -1141.8, -1144.9],
       [-1366. , -1369.9, -1373.8, -1377.7, -1381.6, -1385.5, -1389.4,
        -1393.3, -1397.2, -1401.1, -1405. , -1408.9, -1412.8, -1416.7,
        -1420.6, -1424.5, -1428.4, -14

In [157]:
# field 4x8_8x8n

In [158]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[:4, :8]
b = b[:8, :8 * n]

In [159]:
a @ b

array([[ -28.  ,  -28.28,  -28.56,  -28.84,  -29.12,  -29.4 ,  -29.68,
         -29.96,  -30.24,  -30.52,  -30.8 ,  -31.08,  -31.36,  -31.64,
         -31.92,  -32.2 ],
       [-140.  , -141.88, -143.76, -145.64, -147.52, -149.4 , -151.28,
        -153.16, -155.04, -156.92, -158.8 , -160.68, -162.56, -164.44,
        -166.32, -168.2 ],
       [-252.  , -255.48, -258.96, -262.44, -265.92, -269.4 , -272.88,
        -276.36, -279.84, -283.32, -286.8 , -290.28, -293.76, -297.24,
        -300.72, -304.2 ],
       [-364.  , -369.08, -374.16, -379.24, -384.32, -389.4 , -394.48,
        -399.56, -404.64, -409.72, -414.8 , -419.88, -424.96, -430.04,
        -435.12, -440.2 ]])

In [160]:
# farm 4x8n_8nx8n

In [161]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[:4, :8 * n]
b = b[:8 * n, :8 * n]

In [162]:
a @ b

array([[ -248. ,  -249.2,  -250.4,  -251.6,  -252.8,  -254. ,  -255.2,
         -256.4,  -257.6,  -258.8,  -260. ,  -261.2,  -262.4,  -263.6,
         -264.8,  -266. ],
       [ -728. ,  -732.4,  -736.8,  -741.2,  -745.6,  -750. ,  -754.4,
         -758.8,  -763.2,  -767.6,  -772. ,  -776.4,  -780.8,  -785.2,
         -789.6,  -794. ],
       [-1208. , -1215.6, -1223.2, -1230.8, -1238.4, -1246. , -1253.6,
        -1261.2, -1268.8, -1276.4, -1284. , -1291.6, -1299.2, -1306.8,
        -1314.4, -1322. ],
       [-1688. , -1698.8, -1709.6, -1720.4, -1731.2, -1742. , -1752.8,
        -1763.6, -1774.4, -1785.2, -1796. , -1806.8, -1817.6, -1828.4,
        -1839.2, -1850. ]])

In [164]:
# farm 4x8n_8nx4

In [166]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[:4, :8 * n]
b = b[:8 * n, :4]

In [167]:
a @ b

array([[ -248. ,  -249.2,  -250.4,  -251.6],
       [ -728. ,  -732.4,  -736.8,  -741.2],
       [-1208. , -1215.6, -1223.2, -1230.8],
       [-1688. , -1698.8, -1709.6, -1720.4]])

In [168]:
# ranch 4x8n_8nx8n4

In [169]:
n = 2
k = 4
m = 8 * n + k
a = np.arange(0, m * m).reshape(m, m) / 10
b = a * -1

a = a[-4:, :8 * n]
b = b[:8 * n, :8 * n + k]

In [170]:
a @ b

array([[ -7928. ,  -7980.4,  -8032.8,  -8085.2,  -8137.6,  -8190. ,
         -8242.4,  -8294.8,  -8347.2,  -8399.6,  -8452. ,  -8504.4,
         -8556.8,  -8609.2,  -8661.6,  -8714. ,  -8766.4,  -8818.8,
         -8871.2,  -8923.6],
       [ -8408. ,  -8463.6,  -8519.2,  -8574.8,  -8630.4,  -8686. ,
         -8741.6,  -8797.2,  -8852.8,  -8908.4,  -8964. ,  -9019.6,
         -9075.2,  -9130.8,  -9186.4,  -9242. ,  -9297.6,  -9353.2,
         -9408.8,  -9464.4],
       [ -8888. ,  -8946.8,  -9005.6,  -9064.4,  -9123.2,  -9182. ,
         -9240.8,  -9299.6,  -9358.4,  -9417.2,  -9476. ,  -9534.8,
         -9593.6,  -9652.4,  -9711.2,  -9770. ,  -9828.8,  -9887.6,
         -9946.4, -10005.2],
       [ -9368. ,  -9430. ,  -9492. ,  -9554. ,  -9616. ,  -9678. ,
         -9740. ,  -9802. ,  -9864. ,  -9926. ,  -9988. , -10050. ,
        -10112. , -10174. , -10236. , -10298. , -10360. , -10422. ,
        -10484. , -10546. ]])