In [3]:
import numpy as np

In [4]:
kernel_size = 4
n = 1
k = 2

In [5]:
rows = cols = kernel_size * n + k

In [6]:
A = np.random.rand(rows, cols)
B = np.random.rand(rows, cols)
Cstar = A @ B

In [7]:
first4nrows = np.zeros((4*n, cols))

In [8]:
lastkrrows = np.zeros((k, cols))

In [9]:
# `a` is first 4n rows and 4n columns of A (upper left corner)
a = A[:4*n, :4*n]
# `b` is first 4n rows and last k columns of A (upper right corner)
b = A[:4*n, -k:]
# `c` is last k rows and 4n columns of A (lower left corner)
c = A[-k:, :4*n]
# `d` is last k rows and last k columns of A (lower right corner)
d = A[-k:, -k:]

In [10]:
# `a_prime` is first 4n rows and 4n columns of B (upper left corner)
a_prime = B[:4*n, :4*n]
# `b_prime` is first 4n rows and last k columns of B (upper right corner)
b_prime = B[:4*n, -k:]
# `c_prime` is last k rows and 4n columns of B (lower left corner)
c_prime = B[-k:, :4*n]
# `d_prime` is last k rows and last k columns of B (lower right corner)
d_prime = B[-k:, -k:]

In [11]:
# there are two contributions to the `first4nrows` matrix
# one is [a] * [a_prime][b_prime] where [a] is 4n x 4n and [a_prime][b_prime] is 4n x (4n + k)
# other is [b] * [c_prime][d_prime] where [b] is 4n x k and [c_prime][d_prime] is k x (4n + k)
alpha = a @ np.concatenate((a_prime, b_prime), axis=1)
first4nrows += alpha
beta = b @ np.concatenate((c_prime, d_prime), axis=1)
first4nrows += beta

In [12]:
# there are also two contributions to the `lastkrrows` matrix
# one is [c] * [a_prime][b_prime] where [c] is k x 4n and [a_prime][b_prime] is 4n x (4n + k)
# other is [d] * [c_prime][d_prime] where [d] is k x k and [c_prime][d_prime] is k x (4n + k)
gamma = c @ np.concatenate((a_prime, b_prime), axis=1)
lastkrrows += gamma
delta = d @ np.concatenate((c_prime, d_prime), axis=1)
lastkrrows += delta

In [13]:
combined = np.concatenate((first4nrows, lastkrrows), axis=0)

In [14]:
assert np.allclose(Cstar, combined)

In [15]:
# alpha it self can be split into two parts
alpha_first4n = np.zeros((4*n, 4*n))
alpha_lastk = np.zeros((4*n, k))

In [16]:
alpha_first4n = a @ a_prime
alpha_lastk = a @ b_prime
alpha_combined = np.concatenate((alpha_first4n, alpha_lastk), axis=1)
assert np.allclose(alpha, alpha_combined)

In [17]:
# ear 4x4_4x4n

In [18]:
n = 2
a_4x4 = np.asarray(
    np.arange(0, 16).reshape(4, 4)
)
b_4x4n = np.asarray(
    np.arange(0, 4 * 4 * n).reshape(4, 4 * n)
) * -1

In [19]:
a_4x4, b_4x4n

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11, -12, -13, -14, -15],
        [-16, -17, -18, -19, -20, -21, -22, -23],
        [-24, -25, -26, -27, -28, -29, -30, -31]]))

In [20]:
b_4x4n_1 = b_4x4n[:, :n]
b_4x4n_2 = b_4x4n[:, n:]

In [21]:
expected = a_4x4 @ b_4x4n

In [22]:
part1 = a_4x4 @ b_4x4n_1
part2 = a_4x4 @ b_4x4n_2
combined = np.concatenate((part1, part2), axis=1)

In [23]:
assert np.allclose(expected, combined)

In [24]:
expected

array([[ -112,  -118,  -124,  -130,  -136,  -142,  -148,  -154],
       [ -304,  -326,  -348,  -370,  -392,  -414,  -436,  -458],
       [ -496,  -534,  -572,  -610,  -648,  -686,  -724,  -762],
       [ -688,  -742,  -796,  -850,  -904,  -958, -1012, -1066]])

In [25]:
# field 4x4n_4nx4n

In [26]:
n = 2
a_4x4n = np.asarray(
    np.arange(0, 4 * 4 * n).reshape(4, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * 4 * n * n).reshape(4 * n, 4 * n)
) * -1

In [27]:
expected = a_4x4n @ b_4nx4n

In [28]:
expected

array([[-1120, -1148, -1176, -1204, -1232, -1260, -1288, -1316],
       [-2912, -3004, -3096, -3188, -3280, -3372, -3464, -3556],
       [-4704, -4860, -5016, -5172, -5328, -5484, -5640, -5796],
       [-6496, -6716, -6936, -7156, -7376, -7596, -7816, -8036]])

In [29]:
# farm 4nx4n_4nx4n

In [30]:
n = 2
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [31]:
expected = a_4nx4n @ b_4nx4n

In [32]:
expected

array([[ -1120,  -1148,  -1176,  -1204,  -1232,  -1260,  -1288,  -1316],
       [ -2912,  -3004,  -3096,  -3188,  -3280,  -3372,  -3464,  -3556],
       [ -4704,  -4860,  -5016,  -5172,  -5328,  -5484,  -5640,  -5796],
       [ -6496,  -6716,  -6936,  -7156,  -7376,  -7596,  -7816,  -8036],
       [ -8288,  -8572,  -8856,  -9140,  -9424,  -9708,  -9992, -10276],
       [-10080, -10428, -10776, -11124, -11472, -11820, -12168, -12516],
       [-11872, -12284, -12696, -13108, -13520, -13932, -14344, -14756],
       [-13664, -14140, -14616, -15092, -15568, -16044, -16520, -16996]])

In [33]:
# ear 4x4n_4nxk

In [34]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [35]:
a = a_4nx4n[:4, : 4*n]
b = b_4nx4n[:4*n, :k]

In [36]:
expected = a @ b

In [37]:
expected

array([[-1120],
       [-2912],
       [-4704],
       [-6496]])

In [38]:
# farm 4nx4n_4nxk

In [39]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [40]:
a = a_4nx4n[:, : 4*n]
b = b_4nx4n[:4*n, :k]

In [41]:
expected = a @ b

In [42]:
expected

array([[ -1120,  -1148,  -1176],
       [ -2912,  -3004,  -3096],
       [ -4704,  -4860,  -5016],
       [ -6496,  -6716,  -6936],
       [ -8288,  -8572,  -8856],
       [-10080, -10428, -10776],
       [-11872, -12284, -12696],
       [-13664, -14140, -14616]])

In [43]:
# ear 4xk_kx4n

In [44]:
n = 2
k = 2
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [45]:
a = a_4nx4n[:4, :k]
b = b_4nx4n[:k, :4*n]

In [46]:
a, b

(array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11, -12, -13, -14, -15]]))

In [47]:
expected = a @ b

In [48]:
expected

array([[  -8,   -9,  -10,  -11,  -12,  -13,  -14,  -15],
       [ -72,  -89, -106, -123, -140, -157, -174, -191],
       [-136, -169, -202, -235, -268, -301, -334, -367],
       [-200, -249, -298, -347, -396, -445, -494, -543]])

In [49]:
# farm 4nxk_kx4n

In [50]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [51]:
a = a_4nx4n[:, :k]
b = b_4nx4n[:k, :4*n]

In [52]:
expected = a @ b

In [53]:
expected

array([[   0,    0,    0,    0,    0,    0,    0,    0],
       [   0,   -8,  -16,  -24,  -32,  -40,  -48,  -56],
       [   0,  -16,  -32,  -48,  -64,  -80,  -96, -112],
       [   0,  -24,  -48,  -72,  -96, -120, -144, -168],
       [   0,  -32,  -64,  -96, -128, -160, -192, -224],
       [   0,  -40,  -80, -120, -160, -200, -240, -280],
       [   0,  -48,  -96, -144, -192, -240, -288, -336],
       [   0,  -56, -112, -168, -224, -280, -336, -392]])

In [54]:
# farm_4nxk_kxk

In [55]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12
b_4nx4n = (np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1) + -12

In [56]:
a = a_4nx4n[:, :k]
b = b_4nx4n[:k, :k]

In [57]:
a,b

(array([[12, 13, 14],
        [20, 21, 22],
        [28, 29, 30],
        [36, 37, 38],
        [44, 45, 46],
        [52, 53, 54],
        [60, 61, 62],
        [68, 69, 70]]),
 array([[-12, -13, -14],
        [-20, -21, -22],
        [-28, -29, -30]]))

In [58]:
expected = a @ b

In [59]:
expected

array([[ -796,  -835,  -874],
       [-1276, -1339, -1402],
       [-1756, -1843, -1930],
       [-2236, -2347, -2458],
       [-2716, -2851, -2986],
       [-3196, -3355, -3514],
       [-3676, -3859, -4042],
       [-4156, -4363, -4570]])

In [60]:
# ear_kx4_4x4

In [79]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [80]:
a = a_4nx4n[:k, :4]

In [81]:
b = b_4nx4n[:4, :4]

In [82]:
a_4nx4n

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [83]:
b_4nx4n

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20, -21, -22, -23],
       [-24, -25, -26, -27, -28, -29, -30, -31],
       [-32, -33, -34, -35, -36, -37, -38, -39],
       [-40, -41, -42, -43, -44, -45, -46, -47],
       [-48, -49, -50, -51, -52, -53, -54, -55],
       [-56, -57, -58, -59, -60, -61, -62, -63]])

In [84]:
a, b

(array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[  0,  -1,  -2,  -3],
        [ -8,  -9, -10, -11],
        [-16, -17, -18, -19],
        [-24, -25, -26, -27]]))

In [85]:
a @ b

array([[ -112,  -118,  -124,  -130],
       [ -496,  -534,  -572,  -610],
       [ -880,  -950, -1020, -1090]])

In [86]:
# field kx4_4x4n

In [95]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [96]:
a = a_4nx4n[:k, :4]
b = b_4nx4n[:4, :4 * n]

In [97]:
b

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20, -21, -22, -23],
       [-24, -25, -26, -27, -28, -29, -30, -31]])

In [98]:
a @ b

array([[ -112,  -118,  -124,  -130,  -136,  -142,  -148,  -154],
       [ -496,  -534,  -572,  -610,  -648,  -686,  -724,  -762],
       [ -880,  -950, -1020, -1090, -1160, -1230, -1300, -1370]])

In [99]:
# farm kx4n_4nx4n

In [115]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1

In [116]:
a = a_4nx4n[:k, :4 * n]
b = b_4nx4n[:4 * n, :4 * n]

In [117]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [118]:
b

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20, -21, -22, -23],
       [-24, -25, -26, -27, -28, -29, -30, -31],
       [-32, -33, -34, -35, -36, -37, -38, -39],
       [-40, -41, -42, -43, -44, -45, -46, -47],
       [-48, -49, -50, -51, -52, -53, -54, -55],
       [-56, -57, -58, -59, -60, -61, -62, -63]])

In [119]:
a @ b

array([[-1120, -1148, -1176, -1204, -1232, -1260, -1288, -1316],
       [-2912, -3004, -3096, -3188, -3280, -3372, -3464, -3556],
       [-4704, -4860, -5016, -5172, -5328, -5484, -5640, -5796]])

In [120]:
# farm kx4n_4nxk

In [125]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
)
b_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) * -1
a = a_4nx4n[:k, :4 * n]
b = b_4nx4n[:4 * n, :k]

In [126]:
a @ b

array([[-1120]])

In [127]:
# farm kxk_kx4n

In [158]:
n = 2
k = 3
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12
b_4nx4n = (np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12) * -1
a = a_4nx4n[:k, :k]
b = b_4nx4n[:k, :4 * n]

In [159]:
a @ b

array([[ -796,  -835,  -874,  -913,  -952,  -991, -1030, -1069],
       [-1276, -1339, -1402, -1465, -1528, -1591, -1654, -1717],
       [-1756, -1843, -1930, -2017, -2104, -2191, -2278, -2365]])

In [160]:
# farm kxk_kxk

In [166]:
n = 2
k = 1
a_4nx4n = np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12
b_4nx4n = (np.asarray(
    np.arange(0, 4 * n * 4 * n).reshape(4 * n, 4 * n)
) + 12) * -1
a = a_4nx4n[:k, :k]
b = b_4nx4n[:k, :k]

In [168]:
a @ b

array([[-144]])

In [169]:
# ranch 4nx4n_4nx4nk
# that is, 4n x 4n matrix multiplied by 4n x (4n + k) matrix

In [191]:
n = 2
k = 3
a_4nkx4nk = np.asarray(
    np.arange(0, (4 * n + k) * (4 * n + k)).reshape(4 * n + k, 4 * n + k)
) * 0.1
b_4nkx4nk = a_4nkx4nk * -1

In [192]:
a = a_4nkx4nk[:4 * n, :4 * n]
a_prime = b_4nkx4nk[:4 * n, :4 * n]
b_prime = b_4nkx4nk[:4 * n, 4 * n:]

In [193]:
a @ np.concatenate((a_prime, b_prime), axis=1)

array([[ -15.4 ,  -15.68,  -15.96,  -16.24,  -16.52,  -16.8 ,  -17.08,
         -17.36,  -17.64,  -17.92,  -18.2 ],
       [ -49.28,  -50.44,  -51.6 ,  -52.76,  -53.92,  -55.08,  -56.24,
         -57.4 ,  -58.56,  -59.72,  -60.88],
       [ -83.16,  -85.2 ,  -87.24,  -89.28,  -91.32,  -93.36,  -95.4 ,
         -97.44,  -99.48, -101.52, -103.56],
       [-117.04, -119.96, -122.88, -125.8 , -128.72, -131.64, -134.56,
        -137.48, -140.4 , -143.32, -146.24],
       [-150.92, -154.72, -158.52, -162.32, -166.12, -169.92, -173.72,
        -177.52, -181.32, -185.12, -188.92],
       [-184.8 , -189.48, -194.16, -198.84, -203.52, -208.2 , -212.88,
        -217.56, -222.24, -226.92, -231.6 ],
       [-218.68, -224.24, -229.8 , -235.36, -240.92, -246.48, -252.04,
        -257.6 , -263.16, -268.72, -274.28],
       [-252.56, -259.  , -265.44, -271.88, -278.32, -284.76, -291.2 ,
        -297.64, -304.08, -310.52, -316.96]])

In [195]:
# ranch 4nxk_kx4nk
# that is, 4n x k matrix multiplied by k x (4n + k) matrix

In [227]:
n = 2
k = 1
a_4nkx4nk = np.asarray(
    np.arange(0, (4 * n + k) * (4 * n + k)).reshape(4 * n + k, 4 * n + k)
) * 0.1
b_4nkx4nk = a_4nkx4nk * -1

In [228]:
b = a_4nkx4nk[:4 * n, 4 * n:4 * n + k]
c_prime = b_4nkx4nk[4 * n:4 * n + k, :4 * n]
d_prime = b_4nkx4nk[4 * n:4 * n + k, 4 * n:]

In [229]:
b @ np.concatenate((c_prime, d_prime), axis=1)

array([[ -14.5 ,  -14.67,  -14.84,  -15.01,  -15.18,  -15.35,  -15.52,
         -15.69,  -15.86,  -16.03],
       [ -31.5 ,  -31.87,  -32.24,  -32.61,  -32.98,  -33.35,  -33.72,
         -34.09,  -34.46,  -34.83],
       [ -48.5 ,  -49.07,  -49.64,  -50.21,  -50.78,  -51.35,  -51.92,
         -52.49,  -53.06,  -53.63],
       [ -65.5 ,  -66.27,  -67.04,  -67.81,  -68.58,  -69.35,  -70.12,
         -70.89,  -71.66,  -72.43],
       [ -82.5 ,  -83.47,  -84.44,  -85.41,  -86.38,  -87.35,  -88.32,
         -89.29,  -90.26,  -91.23],
       [ -99.5 , -100.67, -101.84, -103.01, -104.18, -105.35, -106.52,
        -107.69, -108.86, -110.03],
       [-116.5 , -117.87, -119.24, -120.61, -121.98, -123.35, -124.72,
        -126.09, -127.46, -128.83],
       [-133.5 , -135.07, -136.64, -138.21, -139.78, -141.35, -142.92,
        -144.49, -146.06, -147.63]])